create OR REPLACE DATABASE PROC_INFORMATION_SCHEMA;
CREATE OR REPLACE SCHEMA CLASS;
/* iNFORMATION_sCHEMA:

- CONTAINS SET OF  SYSTEM DEFINED VIEWS AND TABLE FUNCTIONS -> PROVIDE EXTENSIVE METADATA INFORMATION ABOUT OBJECTS CREATED IN YOUR ACCOUNT.
-- UTOMATYICALKLY CREATED UPON CREATION OF A DATABASE; 
-- INFORMATION_sCHEMA CONTAINS THE FOLLOWING:
    -- VIEWS FOR ALL OBJECTS CONTAIONED IN THE DATABASE.
    -- VIEWS FOR ACCOUNT_LEVEL OBJECTES(I.E NON DATABASE OBJECTS SUCH AS ROILSES AN DWAREHOIUSES)
*/

/*

-- iMPORTANT vIEWS:


1. TABLES: GIVES COMPLETE DETAILS ABOUT TABLES PRESENT IN ALL THE SCHEMAS OF THAT DATABSE
        - TABLE_CATALOG,
        - TABLE_SCHEMA,
        - TABLE_NAME,
        - TABLE_OWNER,
        - TABLE_TYPE,
        - CLUSTERING_KEY,
        - ROW_COUNT,
        - BYTES, 
        - RETENTION_TIME, 
        - CREATED,
        - LAST_CREATED,
        - LAST_ALTERED,
        - COMMENT ETC.

2. VIEWS: GIVES ADETAILS ABOUT THE VIEWS PRESENT IN ALL TEH SCHEMAS OF THAT DATABASE.
        THE DETAILS INCLUDE TABLE_CATALOG,TABLE_SCHEMA, TABLE_NAME, TABLE_OWNER, VIEW_DFINITION, IS_SECURED, CREATED, LAST_ALTERED, COMMENT ETC. 
3. COLUMNS: GIVES COMPLETE DETAILS OF THE COLUMSN PRESENT IN  ALLK THE TABNLES OF THAT DATABASE.
        - TABLE_CATALOG,
        - TABLE_SCHEMA
        - TABLE_NAME,
        - COLUMN_NAME,
        - DATAT_TYPE,
        - IS_NULLABLE
        - LENGTH,
        - COLUMN_DEFAULT,
        - COMMENT ETC

-- OTHE RIMPORTANT VIEWS:
    -- FUNCTTIONS
    -- PROCEDURES
    -- PIPES
    -- LOAD_HISTORY
    -- EXTERNAL_TABLES
    -- FILE_FORMATS
    -- STAGES
    -- TABLE_CONSTRAINTS
    -- TABLE_PRIVILEGES

---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
