CREATE OR REPLACE DATABASE PROC_SCD1;
CREATE OR REPLACE SCHEMA PROC_SCD1.CLASS;
CREATE OR REPLACE SCHEMA PROC_SCD1.STREAM;
CREATE OR REPLACE SCHEMA PROC_SCD1.TARGET_TABLE;
CREATE OR REPLACE SCHEMA PROC_SCD1.PROC_SCHEMA;


-----------------------------------------------------------------------------------------------------------------
CREATE OR REPLACE TABLE PROC_SCD1.CLASS.LOAN_APPLICATIONS
(

    APPLICATION_ID      STRING,
    APPLICANT_NAME      STRING,
    AGE                 NUMBER(3,0),
    INCOME              NUMBER(10,2),
    CREDIT_SCORE        NUMBER(3,0),
    LOAN_PURPOSE        STRING,
    EMPLOYMENT_STATUS   STRING,
    APPLICATION_DATE    DATE,
    FIRST_INSERT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    VALID_UPTO TIMESTAMP_NTZ DEFAULT NULL
);

-- STREAM CREATION:
CREATE OR REPLACE STREAM PROC_SCD1.STREAM.DUMMY_STREAM 
ON TABLE  PROC_SCD1.CLASS.LOAN_APPLICATIONS;


-- CHECK RECORDS:

SELECT * FROM PROC_SCD1.CLASS.LOAN_APPLICATIONS; -- 0 Records


-- INSERTION OF RECORDS:
INSERT INTO PROC_SCD1.CLASS.LOAN_APPLICATIONS
(APPLICATION_ID, APPLICANT_NAME, AGE, INCOME, CREDIT_SCORE, LOAN_PURPOSE, EMPLOYMENT_STATUS, APPLICATION_DATE)
VALUES 
('APP1001', 'Riya Sharma', 29, 65000.00, 720, 'Home Improvement', 'Employed', '2025-07-01'),
('APP1002', 'Amit Patel', 35, 85000.00, 690, 'Debt Consolidation', 'Self-Employed', '2025-07-02'),
('APP1003', 'Sara Khan', 24, 48000.00, 710, 'Education', 'Student', '2025-07-03'),
('APP1004', 'David Chen', 41, 120000.00, 760, 'Business Expansion', 'Employed', '2025-07-04'),
('APP1005', 'Priya Desai', 32, 73000.00, 680, 'Medical', 'Unemployed', '2025-07-05'),
('APP1006', 'John Thomas', 27, 57000.00, 705, 'Auto Loan', 'Employed', '2025-07-06'),
('APP1007', 'Meera Nair', 38, 95000.00, 740, 'Vacation', 'Employed', '2025-07-07'),
('APP1008', 'Arjun Rao', 45, 130000.00, 750, 'Debt Consolidation', 'Self-Employed', '2025-07-08'),
('APP1009', 'Kavya Iyer', 30, 61000.00, 715, 'Wedding', 'Employed', '2025-07-09'),
('APP1010', 'Rahul Singh', 34, 80000.00, 725, 'Home Purchase', 'Employed', '2025-07-10');




SELECT * FROM PROC_SCD1.CLASS.LOAN_APPLICATIONS;-- 10 RECORDS;

SELECT * FROM PROC_SCD1.STREAM.DUMMY_STREAM; -- 10 records;

-- ONE TIME INGESTION INTO TARGET TABLES

CREATE OR REPLACE TABLE PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS
(

    APPLICATION_ID      STRING,
    APPLICANT_NAME      STRING,
    AGE                 NUMBER(3,0),
    INCOME              NUMBER(10,2),
    CREDIT_SCORE        NUMBER(3,0),
    LOAN_PURPOSE        STRING,
    EMPLOYMENT_STATUS   STRING,
    APPLICATION_DATE    DATE,
    is_active BOOLEAN DEFAULT TRUE,
    FIRST_INSERT_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP,
    VALID_UPTO TIMESTAMP_NTZ DEFAULT NULL
);


INSERT INTO PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS(APPLICATION_ID, APPLICANT_NAME, AGE, INCOME, CREDIT_SCORE, LOAN_PURPOSE, EMPLOYMENT_STATUS, APPLICATION_DATE) SELECT APPLICATION_ID, APPLICANT_NAME, AGE, INCOME, CREDIT_SCORE, LOAN_PURPOSE, EMPLOYMENT_STATUS, APPLICATION_DATE FROM PROC_SCD1.CLASS.LOAN_APPLICATIONS;

SELECT * FROM PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS; -- 10 RECORDS.

SELECT * FROM PROC_SCD1.STREAM.DUMMY_STREAM; -- unused still 10 records.

--------------------------------------------------------------------------------------------------------------------------------------------------

/* SCD TYPE 2 IMPLEMENTATION*/

CREATE OR REPLACE PROCEDURE PROC_SCD1.PROC_SCHEMA.PROC_INGEST()
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS CALLER AS
$$
BEGIN
    CREATE OR REPLACE TEMPORARY TABLE temp_table AS
    SELECT * FROM PROC_SCD1.STREAM.DUMMY_STREAM;

    UPDATE PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS as t
    SET t.IS_ACTIVE = FALSE,
    t.VALID_UPTO = CURRENT_TIMESTAMP
    FROM temp_table as src
    WHERE t.APPLICATION_ID = src.APPLICATION_ID
    AND t.IS_ACTIVE = TRUE
    AND src.METADATA$ACTION = 'DELETE'
    AND src.METADATA$ISUPDATE = TRUE;
  

    INSERT INTO PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS(
        APPLICATION_ID,
        APPLICANT_NAME,
        AGE,
        INCOME,
        CREDIT_SCORE,
        LOAN_PURPOSE,
        EMPLOYMENT_STATUS,
        APPLICATION_DATE
    
    )
    SELECT SRC.APPLICATION_ID, SRC.
APPLICANT_NAME, SRC.AGE, SRC.INCOME, SRC.CREDIT_SCORE, SRC.
LOAN_PURPOSE,SRC.EMPLOYMENT_STATUS,SRC.APPLICATION_DATE
FROM temp_table AS SRC
LEFT JOIN PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS as T
WHERE (T.APPLICATION_ID IS NULL 
AND SRC.METADATA$ACTION = 'INSERT' AND SRC.METADATA$ISUPDATE = FALSE
) OR
(T.APPLICATION_ID = SRC.APPLICATION_ID AND SRC.METADATA$ACTION = 'INSERT' AND SRC.METADATA$ISUPDATE = TRUE);

RETURN 'SC2 IMPLEMENTED';
END;
$$;

CALL PROC_SCD1.PROC_SCHEMA.PROC_INGEST(); -- SC2 IMPLEMENTED o/p

SELECT * FROM PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS; -- 10 records lets update
-- one record from teh source table

//STREM:
SELECT * FROM PROC_SCD1.STREAM.DUMMY_STREAM; -- already used up hence empty

// SOURCE TABLE:
 SELECT * FROM PROC_SCD1.CLASS.LOAN_APPLICATIONS; -- source table

 UPDATE PROC_SCD1.CLASS.LOAN_APPLICATIONS SET EMPLOYMENT_STATUS = 'Retired'
 WHERE APPLICATION_ID = 'APP1001';

 SELECT * from PROC_SCD1.CLASS.LOAN_APPLICATIONS; -- updated for APP1001	Riya Sharma.

 -- lets check the stream :
SELECT * FROM PROC_SCD1.STREAM.DUMMY_STREAM; -- 2 records one with Insert and True => new updated row
-- one with Delete and Metadata$isupdate = True => sugesting the old record

// CALLING THE PROCEDURE:
CALL PROC_SCD1.PROC_SCHEMA.PROC_INGEST(); -- SC2 IMPLEMENTED

// TARGET TABLE CHECK:

SELECT * FROM PROC_SCD1.TARGET_TABLE.TGT_LOAN_APPLICATIONS; -- got two records for RIYA SHARMA => Thus the procedure is working.



--------------------------------------------------------------------------------------------------------------------------------------------------
 
 
    
